name: keepalived
adopt-info: keepalived-415
base: core18
summary: High availability VRRP and load-balancing for Linux
description: |
  Keepalived provides simple and robust loadbalancing and high-availability
  to Linux based infrastructures using VRRP and the well-known Linux Virtual
  Server (IPVS) kernel module.

grade: devel
confinement: devmode

layout:
  /etc/keepalived:
    symlink: $SNAP_DATA/etc/keepalived
  /usr/share/dbus-1/interfaces:
    symlink: $SNAP/usr/share/dbus-1/interfaces

slots:
  dbus-svc: # name that is used with 'snap connect' on slots side
    interface: dbus
    bus: system
    name: org.keepalived.Vrrp1

system-usernames:
   snap_daemon: shared

apps:
  keepalived:
    daemon: forking
    command: usr/sbin/keepalived
  keepalive-cmd:
    command: usr/sbin/keepalived
  genhash:
    command: usr/bin/genhash

parts:
  linux-headers-415:
    plugin: nil
    build-packages:
      - dpkg
      - dpkg-dev
      - wget
    override-pull: |
      KERNEL_VER="4.15.0"
      ARCH=$(dpkg-architecture -q DEB_BUILD_ARCH)
      if [ $ARCH = amd64 ] || [ $ARCH = i386 ]; then
        ARCHIVE_URL="http://security.ubuntu.com/ubuntu/pool/main/l/linux/"
      else
        ARCHIVE_URL="http://ports.ubuntu.com/pool/main/l/linux/"
      fi
      DEB_SUFFIX=$(wget ${ARCHIVE_URL} -O - | grep linux-libc-dev | cut -d'_' -f2-3 | cut -d'"' -f1 | grep ${ARCH} | grep ${KERNEL_VER} | tail -n1)
      wget --quiet ${ARCHIVE_URL}/linux-libc-dev_${DEB_SUFFIX} -O ${SNAPCRAFT_PART_INSTALL}/linux-libc-dev.deb
      echo -n "Unpacking kernel headers..."
      dpkg -x ${SNAPCRAFT_PART_INSTALL}/linux-libc-dev.deb ${SNAPCRAFT_PART_INSTALL}
      printf " %d.%d.%d\n" $(printf "%6.6x" $(grep LINUX_VERSION_CODE ${SNAPCRAFT_PART_INSTALL}/usr/include/linux/version.h | sed -e "s/.*CODE //") | sed -e "s/\(..\)\(..\)/0x\1 0x\2 0x/")
      rm -f ${SNAPCRAFT_PART_INSTALL}/linux-libc-dev.deb
    override-build: |
      snapcraftctl build
      # Move the headers on the host out of the way
      HEADER_DIRS={linux,asm-generic}
      rm -rf /usr/include/${HEADER_DIRS} || true
      # Move header from the part to the host
      mv ${SNAPCRAFT_PART_INSTALL}/usr/include/${HEADER_DIRS} /usr/include/ || true
      echo -n "Build kernel:"
      printf " %d.%d.%d\n" $(printf "%6.6x" $(grep LINUX_VERSION_CODE /usr/include/linux/version.h | sed -e "s/.*CODE //") | sed -e "s/\(..\)\(..\)/0x\1 0x\2 0x/")
    stage:
      - -*
    prime:
      - -*

  keepalived-415:
    plugin: autotools
    source: .
    source-type: git
    after:
      - linux-headers-415
    configflags:
      - --prefix=/usr
      - --enable-bfd
      - --enable-dbus
      - --enable-json
      - --enable-regex
      - --enable-snmp
      - --enable-snmp-rfc
      - --disable-libipset-dynamic
    override-build: |
      snapcraftctl build
      VER=$(grep GIT_COMMIT lib/git-commit.h | cut -d'"' -f2)
      snapcraftctl set-version $VER
    build-packages:
      - libglib2.0-dev
      - libmnl-dev
      - libnftnl-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libpcre2-dev
      - libsnmp-dev
      - libssl-dev
    stage-packages:
      - libjansson4
      - libnftnl7
      - libpci3
      - libpcre2-8-0
      - libperl5.26
      - libsensors4
      - libsnmp30

  keepalived-wrapper:
    plugin: dump
    source: snap-tools
    organize:
      'keepalived-wrapper': bin/
