name: keepalived
adopt-info: keepalived
summary: High availability VRRP and load-balancing for Linux
description: |
  Keepalived provides simple and robust loadbalancing and high-availability
  to Linux based infrastructures using VRRP and the well-known Linux Virtual
  Server (IPVS) kernel module.

base: core
grade: stable
confinement: classic

# linux-libc-dev for 4.18 and 3.10 are no longer available via
#    http://security.ubuntu.com/ubuntu/pool/main/l/linux/
# or
#    http://ports.ubuntu.com/pool/main/l/linux/
# and will disappear for other versions is due course.
#
# To find the relevant files, go to launchpad.net/ubuntu/CODENAME/ARCH/linux-libc-dev
#   where CODENAME is, for example cosmic for Ubuntu 18.10, and ARCH is each of amd64,
#   i386, armhf and s390x.
# Select the most recent version, and click on link under Version column (RHS). Under
#   Downloadable files is a link to the .deb file. That is what we need in DEB_URL.
#
# We should probably update the locations of the files to use this more difficult way
#   of finding them once the Ubuntu version that provides them goes EOL.

apps:
  daemon:
    daemon: forking
    command: bin/keepalived-wrapper
  keepalived:
    command: bin/keepalived-wrapper
  "404":        # Ubuntu 16.04
    command: usr/sbin/keepalived-404
  genhash:
    command: usr/bin/genhash

parts:
  keepalived:
    plugin: autotools
    source: .
    source-type: git
    configflags:
      - --prefix=/usr
      - --enable-bfd
      - --enable-dbus
      - --enable-json
      - --enable-regex
      - --enable-snmp
      - --enable-snmp-rfc
      - --disable-libipset-dynamic
    override-build: |
      snapcraftctl build
      VER=$(grep GIT_COMMIT lib/git-commit.h | cut -d'"' -f2)
      snapcraftctl set-version $VER
      echo -n "Build kernel:"
      printf " %d.%d.%d\n" $(printf "%6.6x" $(grep LINUX_VERSION_CODE /usr/include/linux/version.h | sed -e "s/.*CODE //") | sed -e "s/\(..\)\(..\)/0x\1 0x\2 0x/")
    build-packages:
      - iptables-dev
      - libipset-dev
      - libjson-c-dev
      - libglib2.0-dev
      - libmagic-dev
      - libmnl-dev
      - libnftnl-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnfnetlink-dev
      - libpcre2-dev
      - libsnmp-dev
      - libssl-dev
    stage-packages:
      - libnfnetlink0
      - libipset3
      - libjson-c2
      - libglib2.0-0
      - libmagic1
      - libmnl0
      - libnftnl4
      - libnl-3-200
      - libnl-genl-3-200
      - libpcre2-8-0
      - libsnmp30
    organize:
      'usr/sbin/keepalived': usr/sbin/keepalived-404

  keepalived-wrapper:
    plugin: dump
    source: snap-tools
    organize:
      'keepalived-wrapper': bin/
